package com.app.model;
// Generated 04.05.2017 21:58:56 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userhistory generated by hbm2java
 */
@Entity
@Table(name = "userhistory", catalog = "testing_simulator_db")
public class Userhistory implements java.io.Serializable {

	private Integer id;
	private Task task;
	private User user;
	private String answer;
	private String fileLink;
	private Integer mark;

	public Userhistory() {
	}

	public Userhistory(User user) {
		this.user = user;
	}

	public Userhistory(Task task, User user, String answer, String fileLink, Integer mark) {
		this.task = task;
		this.user = user;
		this.answer = answer;
		this.fileLink = fileLink;
		this.mark = mark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_task")
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "answer", length = 65535)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Column(name = "file_link", length = 100)
	public String getFileLink() {
		return this.fileLink;
	}

	public void setFileLink(String fileLink) {
		this.fileLink = fileLink;
	}

	@Column(name = "mark")
	public Integer getMark() {
		return this.mark;
	}

	public void setMark(Integer mark) {
		this.mark = mark;
	}

}
